# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='primary_nature',
            field=models.CharField(choices=[('CONSOLE', 'Console'), ('CONSOLE_CHIP', 'Console-on-chip'), ('HANDHELD_CONSOLE', 'Handheld Console'), ('Software', (('GAME', 'Game'), ('ADD_ON', 'AddOn'), ('MOD', 'Mod'), ('COMPILATION', 'Compilation'), ('DEMO', 'Demo'), ('OS', 'Os'), ('WEB_BROWSER', 'Web browser'), ('APPLICATION', 'Application'), ('MEDIA', 'Media'))), ('Accessory', (('PAD', 'Pad'), ('ARCADE_STICK', 'Arcade stick'), ('JOYSTICK', 'Joystick'), ('GUN', 'Gun'), ('STEERINGWHEEL', 'Steeringwheel'), ('DRUM', 'Drum'), ('GUITAR', 'Guitar'), ('TURNTABLE', 'Turntable'), ('BATTERY_CHARGER', 'Battery charger'), ('BATTERY_ELEC', 'Electric battery'), ('BUZZER', 'Buzzer'), ('CAMERA', 'Camera'), ('CHEAT_DEV', 'Cheat device'), ('DANCEMAT', 'Dancemat'), ('FISHING_ROD', 'Fishing rod'), ('HEADPHONES', 'Headphones'), ('KEYBOARD', 'Keyboard'), ('LINK_CABLE', 'Link cable'), ('MAGNIFIER', 'Magnifier'), ('MEMORYCARD', 'Memorycard'), ('MICROPHONE', 'Microphone'), ('MODEM', 'Modem'), ('MOTION_SENSING', 'Motion sensing'), ('MOUSE', 'Mouse'), ('MULTITAP', 'Multitap'), ('PRINTER', 'Printer'), ('PROTECTIVE_CASE', 'Protective case'), ('RAM_PACK', 'Ram pack'), ('REGION_UNLOCK', 'Region unlock'), ('RUMBLE_PACK', 'Rumble pack'), ('SCANNER', 'Scanner'), ('SCREEN_MAIN', 'Screen main'), ('SCREEN_INDIV', 'Screen individual'), ('SPEAKERS', 'Speakers'), ('STEREOGLASSES', 'Stereo glasses'), ('TRANSIT_CONTAINER', 'Transit container')))], max_length=17),
        ),
        migrations.AlterField(
            model_name='conceptnature',
            name='nature',
            field=models.CharField(choices=[('CONSOLE', 'Console'), ('CONSOLE_CHIP', 'Console-on-chip'), ('HANDHELD_CONSOLE', 'Handheld Console'), ('Software', (('GAME', 'Game'), ('ADD_ON', 'AddOn'), ('MOD', 'Mod'), ('COMPILATION', 'Compilation'), ('DEMO', 'Demo'), ('OS', 'Os'), ('WEB_BROWSER', 'Web browser'), ('APPLICATION', 'Application'), ('MEDIA', 'Media'))), ('Accessory', (('PAD', 'Pad'), ('ARCADE_STICK', 'Arcade stick'), ('JOYSTICK', 'Joystick'), ('GUN', 'Gun'), ('STEERINGWHEEL', 'Steeringwheel'), ('DRUM', 'Drum'), ('GUITAR', 'Guitar'), ('TURNTABLE', 'Turntable'), ('BATTERY_CHARGER', 'Battery charger'), ('BATTERY_ELEC', 'Electric battery'), ('BUZZER', 'Buzzer'), ('CAMERA', 'Camera'), ('CHEAT_DEV', 'Cheat device'), ('DANCEMAT', 'Dancemat'), ('FISHING_ROD', 'Fishing rod'), ('HEADPHONES', 'Headphones'), ('KEYBOARD', 'Keyboard'), ('LINK_CABLE', 'Link cable'), ('MAGNIFIER', 'Magnifier'), ('MEMORYCARD', 'Memorycard'), ('MICROPHONE', 'Microphone'), ('MODEM', 'Modem'), ('MOTION_SENSING', 'Motion sensing'), ('MOUSE', 'Mouse'), ('MULTITAP', 'Multitap'), ('PRINTER', 'Printer'), ('PROTECTIVE_CASE', 'Protective case'), ('RAM_PACK', 'Ram pack'), ('REGION_UNLOCK', 'Region unlock'), ('RUMBLE_PACK', 'Rumble pack'), ('SCANNER', 'Scanner'), ('SCREEN_MAIN', 'Screen main'), ('SCREEN_INDIV', 'Screen individual'), ('SPEAKERS', 'Speakers'), ('STEREOGLASSES', 'Stereo glasses'), ('TRANSIT_CONTAINER', 'Transit container')))], max_length=17),
        ),
    ]
