# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0002_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagtooccurrence',
            old_name='user',
            new_name='user_creator',
        ),
        migrations.AlterUniqueTogether(
            name='tagtooccurrence',
            unique_together=set([('user_creator', 'user_occurrence_id')]),
        ),
    ]
