# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0003_auto_20160212_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='tag_url',
            field=models.URLField(null=True),
        ),
    ]
