# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0004_auto_20160821_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('category', 'name')},
        ),
    ]
