# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0004_occurrence_tag_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='releasecustomattribute',
            unique_together=set([('category', 'name', 'release', 'note')]),
        ),
    ]
