# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0005_auto_20160216_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_regions',
            field=models.ManyToManyField(blank=True, to='advideogame.ReleaseRegion'),
        ),
    ]
