# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0006_auto_20160222_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringWheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedals', models.BooleanField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='concept',
            name='primary_nature',
            field=models.CharField(choices=[('CONSOLE', 'Console'), ('HANDHELD_CONSOLE', 'Handheld Console'), ('Software', (('GAME', 'Game'), ('ADD_ON', 'AddOn'), ('MOD', 'Mod'), ('DEMO', 'Demo'), ('OS', 'Os'), ('WEB_BROWSER', 'Web browser'), ('APPLICATION', 'Application'), ('MEDIA', 'Media'))), ('Accessory', (('PAD', 'Pad'), ('ARCADE_STICK', 'Arcade stick'), ('JOYSTICK', 'Joystick'), ('GUN', 'Gun'), ('STEERINGWHEEL', 'Steeringwheel'), ('DRUM', 'Drum'), ('GUITAR', 'Guitar'), ('TURNTABLE', 'Turntable'), ('BATTERY_CHARGER', 'Battery charger'), ('BATTERY_ELEC', 'Electric battery'), ('BUZZER', 'Buzzer'), ('CAMERA', 'Camera'), ('CHEAT_DEV', 'Cheat device'), ('DANCEMAT', 'Dancemat'), ('FISHING_ROD', 'Fishing rod'), ('MOTION_SENSING', 'Motion sensing'), ('HEADPHONES', 'Headphones'), ('KEYBOARD', 'Keyboard'), ('LINK_CABLE', 'Link cable'), ('MAGNIFIER', 'Magnifier'), ('MEMORYCARD', 'Memorycard'), ('MICROPHONE', 'Microphone'), ('MODEM', 'Modem'), ('MOUSE', 'Mouse'), ('MULTITAP', 'Multitap'), ('PRINTER', 'Printer'), ('PROTECTIVE_CASE', 'Protective case'), ('RAM_PACK', 'Ram pack'), ('REGION_UNLOCK', 'Region unlock'), ('RUMBLE_PACK', 'Rumble pack'), ('SCANNER', 'Scanner'), ('SCREEN', 'Screen'), ('SPEAKERS', 'Speakers'), ('STEREOGLASSES', 'Stereo glasses')))], max_length=16),
        ),
        migrations.AlterField(
            model_name='conceptnature',
            name='nature',
            field=models.CharField(choices=[('CONSOLE', 'Console'), ('HANDHELD_CONSOLE', 'Handheld Console'), ('Software', (('GAME', 'Game'), ('ADD_ON', 'AddOn'), ('MOD', 'Mod'), ('DEMO', 'Demo'), ('OS', 'Os'), ('WEB_BROWSER', 'Web browser'), ('APPLICATION', 'Application'), ('MEDIA', 'Media'))), ('Accessory', (('PAD', 'Pad'), ('ARCADE_STICK', 'Arcade stick'), ('JOYSTICK', 'Joystick'), ('GUN', 'Gun'), ('STEERINGWHEEL', 'Steeringwheel'), ('DRUM', 'Drum'), ('GUITAR', 'Guitar'), ('TURNTABLE', 'Turntable'), ('BATTERY_CHARGER', 'Battery charger'), ('BATTERY_ELEC', 'Electric battery'), ('BUZZER', 'Buzzer'), ('CAMERA', 'Camera'), ('CHEAT_DEV', 'Cheat device'), ('DANCEMAT', 'Dancemat'), ('FISHING_ROD', 'Fishing rod'), ('MOTION_SENSING', 'Motion sensing'), ('HEADPHONES', 'Headphones'), ('KEYBOARD', 'Keyboard'), ('LINK_CABLE', 'Link cable'), ('MAGNIFIER', 'Magnifier'), ('MEMORYCARD', 'Memorycard'), ('MICROPHONE', 'Microphone'), ('MODEM', 'Modem'), ('MOUSE', 'Mouse'), ('MULTITAP', 'Multitap'), ('PRINTER', 'Printer'), ('PROTECTIVE_CASE', 'Protective case'), ('RAM_PACK', 'Ram pack'), ('REGION_UNLOCK', 'Region unlock'), ('RUMBLE_PACK', 'Rumble pack'), ('SCANNER', 'Scanner'), ('SCREEN', 'Screen'), ('SPEAKERS', 'Speakers'), ('STEREOGLASSES', 'Stereo glasses')))], max_length=16),
        ),
        migrations.AddField(
            model_name='media',
            name='media_types',
            field=models.ManyToManyField(to='advideogame.MediaType'),
        ),
        migrations.AddField(
            model_name='media',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Release'),
        ),
    ]
