# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('advideogame', '0007_auto_20160224_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_feedback', models.BooleanField()),
                ('rumble_feedback', models.BooleanField()),
                ('autofire', models.BooleanField()),
                ('slow', models.BooleanField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Handheld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advideogame.BatteryType')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OccurrencePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_id', models.PositiveIntegerField()),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wireless', models.BooleanField()),
                ('battery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advideogame.BatteryType')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Release')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='release',
        ),
        migrations.RemoveField(
            model_name='console',
            name='release',
        ),
        migrations.RemoveField(
            model_name='steeringwheel',
            name='release',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='battery_type',
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='wireless',
        ),
        migrations.AlterField(
            model_name='concept',
            name='primary_nature',
            field=models.CharField(choices=[('CONSOLE', 'Console'), ('CONSOLE_CHIP', 'Console-on-chip'), ('HANDHELD_CONSOLE', 'Handheld Console'), ('Software', (('GAME', 'Game'), ('ADD_ON', 'AddOn'), ('MOD', 'Mod'), ('DEMO', 'Demo'), ('OS', 'Os'), ('WEB_BROWSER', 'Web browser'), ('APPLICATION', 'Application'), ('MEDIA', 'Media'))), ('Accessory', (('PAD', 'Pad'), ('ARCADE_STICK', 'Arcade stick'), ('JOYSTICK', 'Joystick'), ('GUN', 'Gun'), ('STEERINGWHEEL', 'Steeringwheel'), ('DRUM', 'Drum'), ('GUITAR', 'Guitar'), ('TURNTABLE', 'Turntable'), ('BATTERY_CHARGER', 'Battery charger'), ('BATTERY_ELEC', 'Electric battery'), ('BUZZER', 'Buzzer'), ('CAMERA', 'Camera'), ('CHEAT_DEV', 'Cheat device'), ('DANCEMAT', 'Dancemat'), ('FISHING_ROD', 'Fishing rod'), ('HEADPHONES', 'Headphones'), ('KEYBOARD', 'Keyboard'), ('LINK_CABLE', 'Link cable'), ('MAGNIFIER', 'Magnifier'), ('MEMORYCARD', 'Memorycard'), ('MICROPHONE', 'Microphone'), ('MODEM', 'Modem'), ('MOTION_SENSING', 'Motion sensing'), ('MOUSE', 'Mouse'), ('MULTITAP', 'Multitap'), ('PRINTER', 'Printer'), ('PROTECTIVE_CASE', 'Protective case'), ('RAM_PACK', 'Ram pack'), ('REGION_UNLOCK', 'Region unlock'), ('RUMBLE_PACK', 'Rumble pack'), ('SCANNER', 'Scanner'), ('SCREEN_MAIN', 'Screen main'), ('SCREEN_INDIV', 'Screen individual'), ('SPEAKERS', 'Speakers'), ('STEREOGLASSES', 'Stereo glasses'), ('TRANSIT_CONTAINER', 'Transit container')))], max_length=17),
        ),
        migrations.AlterField(
            model_name='conceptnature',
            name='nature',
            field=models.CharField(choices=[('CONSOLE', 'Console'), ('CONSOLE_CHIP', 'Console-on-chip'), ('HANDHELD_CONSOLE', 'Handheld Console'), ('Software', (('GAME', 'Game'), ('ADD_ON', 'AddOn'), ('MOD', 'Mod'), ('DEMO', 'Demo'), ('OS', 'Os'), ('WEB_BROWSER', 'Web browser'), ('APPLICATION', 'Application'), ('MEDIA', 'Media'))), ('Accessory', (('PAD', 'Pad'), ('ARCADE_STICK', 'Arcade stick'), ('JOYSTICK', 'Joystick'), ('GUN', 'Gun'), ('STEERINGWHEEL', 'Steeringwheel'), ('DRUM', 'Drum'), ('GUITAR', 'Guitar'), ('TURNTABLE', 'Turntable'), ('BATTERY_CHARGER', 'Battery charger'), ('BATTERY_ELEC', 'Electric battery'), ('BUZZER', 'Buzzer'), ('CAMERA', 'Camera'), ('CHEAT_DEV', 'Cheat device'), ('DANCEMAT', 'Dancemat'), ('FISHING_ROD', 'Fishing rod'), ('HEADPHONES', 'Headphones'), ('KEYBOARD', 'Keyboard'), ('LINK_CABLE', 'Link cable'), ('MAGNIFIER', 'Magnifier'), ('MEMORYCARD', 'Memorycard'), ('MICROPHONE', 'Microphone'), ('MODEM', 'Modem'), ('MOTION_SENSING', 'Motion sensing'), ('MOUSE', 'Mouse'), ('MULTITAP', 'Multitap'), ('PRINTER', 'Printer'), ('PROTECTIVE_CASE', 'Protective case'), ('RAM_PACK', 'Ram pack'), ('REGION_UNLOCK', 'Region unlock'), ('RUMBLE_PACK', 'Rumble pack'), ('SCANNER', 'Scanner'), ('SCREEN_MAIN', 'Screen main'), ('SCREEN_INDIV', 'Screen individual'), ('SPEAKERS', 'Speakers'), ('STEREOGLASSES', 'Stereo glasses'), ('TRANSIT_CONTAINER', 'Transit container')))], max_length=17),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Console',
        ),
        migrations.DeleteModel(
            name='SteeringWheel',
        ),
    ]
