# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0008_auto_20160228_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencepicture',
            name='detail',
            field=models.CharField(choices=[('GRP', 'Group'), ('FRT', 'Front'), ('BCK', 'Back'), ('SID', 'Side'), ('SLB', 'Side label'), ('INS', 'Inside'), ('DEF', 'Defect')], default='GRP', max_length=3),
        ),
    ]
