# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 14:03
from __future__ import unicode_literals

import advideogame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0009_occurrencepicture_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencepicture',
            name='image_file',
            field=models.ImageField(default=0, upload_to=advideogame.models.name_occurrence_picture),
            preserve_default=False,
        ),
    ]
