# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0010_occurrencepicture_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencepicture',
            name='attribute_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='occurrencepicture',
            name='attribute_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
