# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 15:36
from __future__ import unicode_literals

import advideogame.models
from advideogame.models import name_instance_picture
from functools import partial
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0011_auto_20160229_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundlePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=partial(name_instance_picture, base_model_access=lambda x: x.bundle))),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Bundle')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=partial(name_instance_picture, base_model_access=lambda x: x.release))),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Release')),
            ],
        ),
    ]
