# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:36
from __future__ import unicode_literals

import advideogame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0012_bundlepicture_releasepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='releaseattribute',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='releaseattribute',
            name='code_type',
            field=models.CharField(blank=True, choices=[('S', 'Serial number'), ('C', 'Catalog / Internal')], max_length=1),
        ),
        migrations.AddField(
            model_name='releasecustomattribute',
            name='code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='releasecustomattribute',
            name='code_type',
            field=models.CharField(blank=True, choices=[('S', 'Serial number'), ('C', 'Catalog / Internal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='bundlepicture',
            name='image_file',
            field=models.ImageField(upload_to=advideogame.models.name_bundle_picture),
        ),
        migrations.AlterField(
            model_name='releasepicture',
            name='image_file',
            field=models.ImageField(upload_to=advideogame.models.name_release_picture),
        ),
    ]
