# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0013_auto_20160229_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='unique_number',
            field=models.CharField(blank=True, help_text='An identifier uniquely attached to this occurrence (eg. collector numbered edition).', max_length=32),
        ),
    ]
