# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0014_occurrence_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='digitally_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
