# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advideogame', '0015_release_digitally_distributed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='concept',
            name='url',
        ),
        migrations.AddField(
            model_name='concepturl',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advideogame.Concept'),
        ),
    ]
