# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.Person'),
        ),
    ]
