# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 11:58
from __future__ import unicode_literals

from django.db import migrations

## Implementer note: 
## manage.py migrate fails when there are "multiple leaf nodes in the migrations graph"
## (i.e., more than one migration without another migration depending on it)
## Create a merge migration, to depend on what would otherwise be two leaves

class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_superuser_datamigration'),
        ('supervisor', '0002_initial_data'),
    ]
